all lec2 lec3 lec4

Lec2: Program2_1 Program2_2

Lec3: Program3_1 Program3_2 Program3_3

Lec4: Program4_1 Program4_2 Program4_3

Program2_1:
	gcc 'task1/Lec2/program2_1/' -o 'task1/Lec2/program2_1/Program2_1.out'

Program2_2:
	gcc 'task1/Lec2/program2_2/' -o 'task1/Lec2/program2_2/Program2_2.out'

Program3_1:
	gcc 'task1/Lec3/program3_1/' -o 'task1/Lec3/program3_1/Program3_1.out'

Program3_2:
	gcc 'task1/Lec3/program3_2/' -o 'task1/Lec3/program3_2/Program3_2.out'

Program3_3:
	gcc 'task1/Lec3/program3_3/' -o 'task1/Lec3/program3_3/Program3_3.out'

Program4_1:
	gcc 'task1/Lec4/program4_1/' -o 'task1/Lec4/program4_1/Program4_1.out'

Program4_2:
	gcc 'task1/Lec4/program4_2/' -o 'task1/Lec4/program4_2/Program4_2.out'

Program4_3:
	gcc 'task1/Lec4/program4_3/' -o 'task1/Lec4/program4_3/Program4_3.out'

clear:
	rm -rf task1/Lec*/*.out